const icons = [
  "subject_1.png",
  "subject_2.png",
  "subject_3.png",
  "subject_4.png",
  "subject_5.png",
  "subject_6.png",
  "subject_7.png",
  "subject_8.png",
  "subject_9.png",
  "subject_10.png",
  "subject_11.png",
  "subject_12.png",
  "subject_13.png",
  "subject_14.png",
  "subject_15.png",
  "subject_16.png",
  "subject_17.png",
  "subject_18.png",
  "subject_19.png",
  "subject_20.png",
  "subject_21.png",
  "subject_22.png",
  "subject_23.png",
  "subject_24.png",
  "subject_25.png",
  "subject_26.png",
  "subject_27.png",
  "subject_28.png",
  "subject_29.png",
];

module.exports = icons;
